extends RefCounted
## Todos os dados do jogo: habilidades, formas (Mimetismo), monstros, chefes,
## personagens, áreas e a história completa (arcos do anime e do mangá).
## Para adicionar conteúdo novo basta editar este arquivo.

# ======================================================================= HABILIDADES
## kind: "active" (pode ir para um slot) ou "passive".
## short: texto curto usado nos botões de toque.
const SKILLS := {
	"predator": {"name": "Predador", "kind": "passive", "desc": "Devora monstros derrotados, itens e até dragões. Copia as habilidades do que devora. (Botão PREDADOR / E)"},
	"great_sage": {"name": "Grande Sábio", "kind": "passive", "desc": "Analisa tudo, responde perguntas e dá avisos. Mostra a vida dos inimigos."},
	"raphael": {"name": "Raphael, Senhor da Sabedoria", "kind": "passive", "desc": "Evolução do Grande Sábio no Festival da Colheita. +25% de dano em todas as habilidades."},
	"ciel_passive": {"name": "Ciel (Manas)", "kind": "passive", "desc": "Raphael ganhou um nome e virou um ser próprio: Ciel. Recarga das habilidades 30% mais rápida."},
	"hydraulic": {"name": "Propulsão Hidráulica", "kind": "passive", "desc": "Jato d'água para um pulo duplo no ar."},
	"body_armor": {"name": "Armadura Corporal", "kind": "passive", "desc": "Copiada do Armadurossauro: -20% de dano recebido."},
	"self_regen": {"name": "Autorregeneração", "kind": "passive", "desc": "Recupera vida aos poucos, mais rápido a cada nível."},
	"magic_sense": {"name": "Sentido Mágico", "kind": "passive", "desc": "Permite 'ver' o mundo através das magículas. Mostra o marcador de objetivo."},
	"mimicry": {"name": "Mimetismo", "kind": "passive", "desc": "Assume a forma de algo que foi devorado. (Botão FORMA / T)"},
	"shadow_motion": {"name": "Movimento Sombrio", "kind": "passive", "desc": "Copiado do Lobo Atroz: a esquiva vira um teleporte pelas sombras, mais longo e invulnerável."},
	"water_blade": {"name": "Lâmina d'Água", "short": "LÂMINA", "kind": "active", "mp": 8.0, "cd": 0.35, "desc": "Disparo de água em alta pressão."},
	"poison_breath": {"name": "Sopro Venenoso", "short": "VENENO", "kind": "active", "mp": 20.0, "cd": 2.0, "desc": "Névoa em cone que envenena (Serpente Tempestade)."},
	"paralyze_breath": {"name": "Sopro Paralisante", "short": "PARALISA", "kind": "active", "mp": 22.0, "cd": 4.0, "desc": "Névoa em cone que paralisa (Centopeia Maligna)."},
	"sticky_thread": {"name": "Fio Pegajoso", "short": "FIO", "kind": "active", "mp": 12.0, "cd": 1.0, "desc": "Prende o inimigo no lugar (Aranha Negra)."},
	"ultrasound": {"name": "Ondas Ultrassônicas", "short": "ULTRASSOM", "kind": "active", "mp": 25.0, "cd": 4.0, "desc": "Atordoa todos em volta (Morcego Gigante)."},
	"black_lightning": {"name": "Raio Negro", "short": "RAIO", "kind": "active", "mp": 30.0, "cd": 3.0, "desc": "Raios negros caem sobre o alvo e os inimigos próximos (Lobo Estelar Tempest)."},
	"flame_control": {"name": "Manipulação de Chamas", "short": "CHAMAS", "kind": "active", "mp": 18.0, "cd": 1.2, "desc": "Bola de fogo que explode (herdada de Shizu e Ifrit)."},
	"hell_flare": {"name": "Hell Flare", "short": "INFERNO", "kind": "active", "mp": 45.0, "cd": 6.0, "desc": "Cúpula de chamas negras que incinera uma área (técnica do Benimaru)."},
	"thought_accel": {"name": "Aceleração de Pensamento", "short": "ACELERA", "kind": "active", "mp": 30.0, "cd": 20.0, "desc": "Por 8 s o mundo fica em câmera lenta para os inimigos."},
	"starved": {"name": "Faminto", "short": "FAMINTO", "kind": "active", "mp": 35.0, "cd": 8.0, "desc": "Corrói os inimigos em volta e rouba a vida deles (herdado de Geld, o Lorde Orc)."},
	"megiddo": {"name": "Megiddo", "short": "MEGIDDO", "kind": "active", "mp": 80.0, "cd": 15.0, "desc": "Gotas d'água no céu viram lentes e disparam raios de luz solar em até 10 inimigos."},
	"beelzebuth": {"name": "Belzebu, Senhor da Gula", "short": "BELZEBU", "kind": "active", "mp": 100.0, "cd": 25.0, "desc": "Devora tudo numa área enorme. Monstros fracos são devorados na hora."},
	"storm_dragon": {"name": "Tempestade de Veldora", "short": "VELDORA", "kind": "active", "mp": 120.0, "cd": 30.0, "desc": "Libera o poder do Veldora: um tornado negro que avança destruindo tudo."},
	"disintegration": {"name": "Desintegração", "short": "DESINTEG", "kind": "active", "mp": 90.0, "cd": 12.0, "desc": "Magia sagrada suprema: um feixe que apaga o alvo da existência (analisada da Hinata)."},
	"demon_aura": {"name": "Aura de Lorde Demônio", "short": "AURA", "kind": "active", "mp": 40.0, "cd": 10.0, "desc": "Libera a aura de Lorde Demônio: medo atordoa os inimigos e cura os aliados."},
	"ciel_mode": {"name": "Ciel: Batalha Automática", "short": "CIEL", "kind": "active", "mp": 60.0, "cd": 40.0, "desc": "Por 15 s: dano x2, mira automática e magículas infinitas."},
}

# ======================================================================= FORMAS (Mimetismo)
const FORMS := {
	"slime": {"name": "Slime", "speed": 7.5, "jump": 9.5, "dmg": 1.0, "def": 1.0, "melee": "tackle", "desc": "Forma original. Pulo elástico e corpo resistente."},
	"bat": {"name": "Morcego Gigante", "speed": 8.0, "jump": 7.0, "dmg": 0.8, "def": 0.9, "melee": "bite", "fly": true, "desc": "Segure PULO para voar."},
	"wolf": {"name": "Lobo Estelar Tempest", "speed": 13.5, "jump": 10.5, "dmg": 1.3, "def": 1.1, "melee": "bite", "desc": "Muito rápido. Mordida forte."},
	"human": {"name": "Humano (Shizu)", "speed": 8.5, "jump": 9.5, "dmg": 1.5, "def": 1.0, "melee": "sword", "desc": "Forma humana herdada de Shizu. Golpes com a katana do Kurobe."},
	"demon_lord": {"name": "Lorde Demônio", "speed": 10.5, "jump": 11.0, "dmg": 2.4, "def": 1.7, "melee": "sword", "fly": true, "desc": "Rimuru após o Festival da Colheita. Asas negras (voa) e poder absurdo."},
}
const FORM_ORDER := ["slime", "bat", "wolf", "human", "demon_lord"]

# ======================================================================= MODELOS DE PERSONAGENS
const C_SKIN := Color(0.98, 0.86, 0.76)
const MODELS := {
	"rimuru_human": {"kind": "humanoid", "skin": Color(0.97, 0.9, 0.86), "hair": Color(0.45, 0.78, 0.98), "hair_style": "long", "outfit": Color(0.12, 0.12, 0.18), "outfit2": Color(0.95, 0.95, 1.0), "eye": Color(1.0, 0.8, 0.2), "weapon": "katana", "coat": true, "height": 0.9, "mask": true},
	"rimuru_demon": {"kind": "humanoid", "skin": Color(0.97, 0.9, 0.86), "hair": Color(0.5, 0.82, 1.0), "hair_glow": 0.5, "hair_style": "long", "outfit": Color(0.05, 0.05, 0.08), "outfit2": Color(0.8, 0.7, 0.3), "eye": Color(1.0, 0.75, 0.15), "weapon": "katana", "coat": true, "height": 0.95, "wings": Color(0.08, 0.05, 0.15), "wing_glow": 0.6, "aura": Color(0.5, 0.4, 1.0)},
	"veldora_human": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.98, 0.85, 0.3), "hair_style": "spiky", "outfit": Color(0.1, 0.1, 0.12), "outfit2": Color(0.9, 0.75, 0.2), "eye": Color(1.0, 0.8, 0.1), "height": 1.12, "coat": true},
	"ranga": {"kind": "quadruped", "color": Color(0.1, 0.1, 0.13), "horn": true, "star": true, "scale": 1.35},
	"gobta": {"kind": "humanoid", "skin": Color(0.45, 0.68, 0.38), "hair": Color(0.12, 0.12, 0.1), "hair_style": "short", "outfit": Color(0.45, 0.32, 0.2), "outfit2": Color(0.7, 0.6, 0.4), "height": 0.75, "weapon": "sword"},
	"goblin": {"kind": "humanoid", "skin": Color(0.42, 0.62, 0.35), "hair_style": "bald", "outfit": Color(0.4, 0.3, 0.2), "outfit2": Color(0.5, 0.42, 0.3), "height": 0.62, "weapon": "club", "ears": "elf"},
	"rigurd": {"kind": "humanoid", "skin": Color(0.48, 0.66, 0.4), "hair": Color(0.85, 0.85, 0.85), "hair_style": "short", "outfit": Color(0.35, 0.4, 0.6), "outfit2": Color(0.8, 0.7, 0.3), "height": 1.15, "bulk": 1.35, "ears": "elf"},
	"benimaru": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.85, 0.12, 0.1), "hair_style": "spiky", "outfit": Color(0.15, 0.12, 0.12), "outfit2": Color(0.8, 0.15, 0.1), "eye": Color(0.9, 0.1, 0.1), "horns": 2, "weapon": "katana", "height": 1.05},
	"shuna": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.98, 0.75, 0.85), "hair_style": "long", "outfit": Color(0.97, 0.97, 0.97), "outfit2": Color(0.85, 0.2, 0.35), "eye": Color(0.85, 0.2, 0.4), "horns": 2, "horn_color": Color(0.95, 0.95, 0.95), "skirt": true, "weapon": "staff", "height": 0.92},
	"shion": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.45, 0.25, 0.65), "hair_style": "pony", "outfit": Color(0.1, 0.1, 0.15), "outfit2": Color(0.6, 0.3, 0.8), "eye": Color(0.6, 0.3, 0.8), "horns": 1, "weapon": "greatsword", "skirt": true, "height": 1.02},
	"souei": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.12, 0.18, 0.35), "hair_style": "pony", "outfit": Color(0.08, 0.1, 0.18), "outfit2": Color(0.2, 0.3, 0.5), "eye": Color(0.3, 0.5, 0.9), "horns": 1, "horn_color": Color(0.9, 0.9, 0.95), "weapon": "sword", "height": 1.05},
	"hakurou": {"kind": "humanoid", "skin": Color(0.93, 0.82, 0.72), "hair": Color(0.95, 0.95, 0.95), "hair_style": "pony", "outfit": Color(0.3, 0.38, 0.3), "outfit2": Color(0.9, 0.9, 0.85), "horns": 2, "horn_color": Color(0.9, 0.9, 0.9), "weapon": "katana", "beard": true, "height": 0.95},
	"kurobe": {"kind": "humanoid", "skin": Color(0.85, 0.7, 0.6), "hair": Color(0.15, 0.15, 0.15), "hair_style": "short", "outfit": Color(0.4, 0.3, 0.2), "outfit2": Color(0.2, 0.2, 0.2), "horns": 2, "weapon": "hammer", "bulk": 1.25},
	"gabiru": {"kind": "humanoid", "skin": Color(0.3, 0.6, 0.35), "hair_style": "bald", "outfit": Color(0.6, 0.2, 0.15), "outfit2": Color(0.9, 0.75, 0.2), "snout": true, "tail": Color(0.3, 0.6, 0.35), "weapon": "spear", "cape": Color(0.75, 0.15, 0.15), "height": 1.1},
	"lizardman": {"kind": "humanoid", "skin": Color(0.25, 0.5, 0.3), "hair_style": "bald", "outfit": Color(0.4, 0.35, 0.2), "snout": true, "tail": Color(0.25, 0.5, 0.3), "weapon": "spear"},
	"geld_new": {"kind": "humanoid", "skin": Color(0.6, 0.55, 0.45), "hair": Color(0.3, 0.25, 0.2), "hair_style": "short", "outfit": Color(0.5, 0.45, 0.35), "outfit2": Color(0.7, 0.65, 0.5), "snout": true, "tusks": true, "weapon": "club", "height": 1.3, "bulk": 1.5},
	"orc": {"kind": "humanoid", "skin": Color(0.55, 0.5, 0.35), "hair_style": "bald", "outfit": Color(0.35, 0.28, 0.2), "outfit2": Color(0.45, 0.4, 0.3), "snout": true, "tusks": true, "weapon": "club", "height": 1.15, "bulk": 1.4},
	"orc_knight": {"kind": "humanoid", "skin": Color(0.5, 0.45, 0.32), "outfit": Color(0.3, 0.3, 0.35), "outfit2": Color(0.6, 0.6, 0.65), "snout": true, "tusks": true, "helmet": true, "weapon": "greatsword", "height": 1.25, "bulk": 1.5},
	"geld": {"kind": "humanoid", "skin": Color(0.45, 0.4, 0.3), "hair": Color(0.2, 0.15, 0.1), "hair_style": "spiky", "outfit": Color(0.25, 0.1, 0.1), "outfit2": Color(0.7, 0.6, 0.2), "snout": true, "tusks": true, "eye": Color(1.0, 0.85, 0.1), "weapon": "club", "height": 1.7, "bulk": 1.8, "cape": Color(0.35, 0.05, 0.05), "aura": Color(0.9, 0.7, 0.2)},
	"diablo": {"kind": "humanoid", "skin": Color(0.96, 0.92, 0.9), "hair": Color(0.05, 0.05, 0.07), "hair_style": "short", "outfit": Color(0.06, 0.06, 0.08), "outfit2": Color(0.7, 0.1, 0.15), "eye": Color(1.0, 0.75, 0.1), "coat": true, "height": 1.12, "aura": Color(0.6, 0.1, 0.15)},
	"milim": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.98, 0.45, 0.65), "hair_style": "twin", "outfit": Color(0.08, 0.08, 0.1), "outfit2": Color(0.9, 0.2, 0.3), "eye": Color(0.3, 0.6, 1.0), "height": 0.8, "skirt": true, "aura": Color(1.0, 0.4, 0.6)},
	"treyni": {"kind": "humanoid", "skin": Color(0.85, 0.95, 0.85), "hair": Color(0.3, 0.75, 0.4), "hair_style": "long", "outfit": Color(0.3, 0.6, 0.35), "outfit2": Color(0.9, 0.95, 0.8), "glow": 0.4, "skirt": true, "ears": "elf", "height": 1.05},
	"kaijin": {"kind": "humanoid", "skin": Color(0.9, 0.72, 0.6), "hair": Color(0.45, 0.25, 0.12), "hair_style": "short", "beard": true, "outfit": Color(0.45, 0.3, 0.2), "outfit2": Color(0.3, 0.3, 0.3), "weapon": "hammer", "height": 0.75, "bulk": 1.45},
	"dwarf": {"kind": "humanoid", "skin": Color(0.9, 0.72, 0.6), "hair": Color(0.5, 0.3, 0.15), "hair_style": "short", "beard": true, "outfit": Color(0.35, 0.3, 0.4), "outfit2": Color(0.6, 0.5, 0.3), "weapon": "hammer", "height": 0.72, "bulk": 1.4},
	"gazel": {"kind": "humanoid", "skin": Color(0.9, 0.72, 0.6), "hair": Color(0.3, 0.2, 0.1), "hair_style": "short", "beard": true, "outfit": Color(0.6, 0.5, 0.15), "outfit2": Color(0.8, 0.1, 0.1), "cape": Color(0.6, 0.05, 0.05), "weapon": "sword", "height": 0.95, "bulk": 1.5},
	"shizu": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.08, 0.08, 0.1), "hair_style": "long", "outfit": Color(0.25, 0.22, 0.2), "outfit2": Color(0.8, 0.2, 0.15), "mask": true, "cape": Color(0.3, 0.25, 0.22), "weapon": "sword"},
	"kabal": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.4, 0.25, 0.1), "hair_style": "short", "outfit": Color(0.5, 0.5, 0.55), "outfit2": Color(0.4, 0.3, 0.2), "weapon": "sword", "bulk": 1.2},
	"eren": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.95, 0.8, 0.4), "hair_style": "twin", "outfit": Color(0.4, 0.55, 0.3), "outfit2": Color(0.8, 0.7, 0.5), "ears": "elf", "weapon": "staff", "height": 0.9, "skirt": true},
	"gido": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.2, 0.15, 0.1), "hair_style": "short", "outfit": Color(0.25, 0.3, 0.25), "outfit2": Color(0.5, 0.4, 0.3), "weapon": "sword", "height": 0.95},
	"ifrit": {"kind": "humanoid", "skin": Color(1.0, 0.45, 0.1), "glow": 2.5, "hair": Color(1.0, 0.8, 0.2), "hair_glow": 3.0, "hair_style": "spiky", "outfit": Color(0.9, 0.25, 0.05), "eye": Color(1.0, 1.0, 0.6), "height": 1.6, "aura": Color(1.0, 0.5, 0.1), "weapon": "claws"},
	"ogre": {"kind": "humanoid", "skin": Color(0.85, 0.55, 0.45), "hair": Color(0.2, 0.15, 0.12), "hair_style": "spiky", "outfit": Color(0.35, 0.25, 0.2), "outfit2": Color(0.6, 0.5, 0.3), "horns": 2, "weapon": "club", "height": 1.35, "bulk": 1.4},
	"ogre_prince": {"kind": "humanoid", "skin": Color(0.88, 0.6, 0.5), "hair": Color(0.8, 0.12, 0.1), "hair_style": "spiky", "outfit": Color(0.3, 0.12, 0.1), "outfit2": Color(0.7, 0.2, 0.1), "horns": 2, "weapon": "katana", "height": 1.4, "bulk": 1.3, "aura": Color(1.0, 0.3, 0.1)},
	"soldier": {"kind": "humanoid", "skin": C_SKIN, "outfit": Color(0.55, 0.57, 0.62), "outfit2": Color(0.2, 0.3, 0.6), "helmet": true, "weapon": "sword", "cape": Color(0.15, 0.2, 0.5)},
	"knight": {"kind": "humanoid", "skin": C_SKIN, "outfit": Color(0.8, 0.8, 0.85), "outfit2": Color(0.9, 0.75, 0.2), "helmet": true, "helmet_color": Color(0.85, 0.85, 0.9), "weapon": "spear", "height": 1.1, "bulk": 1.2},
	"mage": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.5, 0.45, 0.4), "hair_style": "long", "outfit": Color(0.3, 0.15, 0.45), "outfit2": Color(0.8, 0.7, 0.3), "coat": true, "weapon": "staff"},
	"shogo": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.25, 0.2, 0.15), "hair_style": "spiky", "outfit": Color(0.3, 0.3, 0.35), "outfit2": Color(0.7, 0.2, 0.2), "eye": Color(0.9, 0.2, 0.2), "weapon": "claws", "bulk": 1.25, "aura": Color(0.9, 0.3, 0.2)},
	"clayman": {"kind": "humanoid", "skin": Color(0.92, 0.88, 0.9), "hair": Color(0.85, 0.82, 0.9), "hair_style": "long", "outfit": Color(0.35, 0.15, 0.45), "outfit2": Color(0.9, 0.8, 0.3), "eye": Color(0.8, 0.2, 0.6), "coat": true, "height": 1.15, "cape": Color(0.25, 0.05, 0.3), "aura": Color(0.7, 0.2, 0.8)},
	"marionette": {"kind": "humanoid", "skin": Color(0.85, 0.82, 0.8), "hair_style": "bald", "outfit": Color(0.45, 0.2, 0.5), "outfit2": Color(0.2, 0.1, 0.2), "no_eyes": true, "weapon": "claws", "bulk": 0.8},
	"hinata": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.06, 0.06, 0.1), "hair_style": "long", "outfit": Color(0.92, 0.92, 0.97), "outfit2": Color(0.2, 0.35, 0.8), "eye": Color(0.3, 0.4, 0.8), "weapon": "sword", "cape": Color(0.9, 0.9, 0.95), "aura": Color(0.8, 0.9, 1.0)},
	"imperial": {"kind": "humanoid", "skin": C_SKIN, "outfit": Color(0.25, 0.3, 0.22), "outfit2": Color(0.6, 0.55, 0.3), "helmet": true, "helmet_color": Color(0.3, 0.35, 0.28), "weapon": "gun"},
	"magic_tank": {"kind": "machine", "color": Color(0.3, 0.34, 0.26)},
	"kondo": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.1, 0.1, 0.1), "hair_style": "short", "outfit": Color(0.18, 0.22, 0.16), "outfit2": Color(0.8, 0.7, 0.3), "weapon": "gun", "coat": true, "height": 1.08, "aura": Color(0.9, 0.9, 0.6)},
	"yuuki": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.1, 0.1, 0.12), "hair_style": "short", "outfit": Color(0.15, 0.15, 0.25), "outfit2": Color(0.9, 0.9, 0.9), "eye": Color(0.5, 0.1, 0.1), "height": 0.98, "aura": Color(0.5, 0.0, 0.2)},
	"guy": {"kind": "humanoid", "skin": Color(0.95, 0.88, 0.85), "hair": Color(0.85, 0.05, 0.1), "hair_style": "long", "outfit": Color(0.6, 0.05, 0.08), "outfit2": Color(0.95, 0.9, 0.85), "eye": Color(1.0, 0.8, 0.1), "coat": true, "height": 1.15, "aura": Color(1.0, 0.1, 0.1)},
	"leon": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.98, 0.88, 0.5), "hair_style": "long", "outfit": Color(0.95, 0.95, 0.95), "outfit2": Color(0.3, 0.4, 0.8), "weapon": "sword", "height": 1.1},
	"luminous": {"kind": "humanoid", "skin": Color(0.98, 0.95, 0.95), "hair": Color(0.92, 0.92, 0.98), "hair_style": "long", "outfit": Color(0.1, 0.05, 0.1), "outfit2": Color(0.8, 0.1, 0.2), "eye": Color(0.9, 0.1, 0.2), "skirt": true, "height": 0.92},
	"ramiris": {"kind": "fairy", "skin": C_SKIN, "hair": Color(0.4, 0.55, 0.95), "hair_style": "long", "outfit": Color(0.9, 0.9, 1.0), "outfit2": Color(0.5, 0.7, 1.0), "skirt": true, "height": 0.45},
	"dagruel": {"kind": "humanoid", "skin": Color(0.75, 0.6, 0.5), "hair": Color(0.5, 0.3, 0.2), "hair_style": "spiky", "outfit": Color(0.45, 0.35, 0.25), "outfit2": Color(0.7, 0.6, 0.3), "beard": true, "height": 1.8, "bulk": 1.5},
	"deeno": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.4, 0.4, 0.45), "hair_style": "short", "outfit": Color(0.3, 0.32, 0.4), "outfit2": Color(0.9, 0.9, 0.9), "wings": Color(0.95, 0.95, 1.0)},
	"frey": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.2, 0.35, 0.3), "hair_style": "long", "outfit": Color(0.2, 0.4, 0.35), "outfit2": Color(0.8, 0.7, 0.4), "wings": Color(0.3, 0.55, 0.45), "skirt": true},
	"carillon": {"kind": "humanoid", "skin": Color(0.9, 0.78, 0.6), "hair": Color(0.9, 0.7, 0.3), "hair_style": "spiky", "outfit": Color(0.5, 0.3, 0.15), "outfit2": Color(0.9, 0.8, 0.5), "ears": "beast", "height": 1.2, "bulk": 1.35, "weapon": "claws"},
	"elmesia": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.95, 0.9, 0.7), "hair_style": "long", "outfit": Color(0.95, 0.95, 0.9), "outfit2": Color(0.3, 0.7, 0.4), "ears": "elf", "skirt": true, "height": 1.0},
	"kids": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.45, 0.3, 0.2), "hair_style": "short", "outfit": Color(0.2, 0.25, 0.45), "outfit2": Color(0.9, 0.9, 0.9), "height": 0.62},
	"chloe": {"kind": "humanoid", "skin": C_SKIN, "hair": Color(0.08, 0.08, 0.12), "hair_style": "long", "outfit": Color(0.2, 0.25, 0.45), "outfit2": Color(0.9, 0.9, 0.9), "height": 0.62, "skirt": true},
	"boar": {"kind": "quadruped", "color": Color(0.4, 0.28, 0.18), "tusks": true, "eye": Color(1, 0.3, 0.1), "mane": Color(0.25, 0.15, 0.1), "scale": 1.0},
	"direwolf": {"kind": "quadruped", "color": Color(0.35, 0.35, 0.4), "star": true},
	"direwolf_leader": {"kind": "quadruped", "color": Color(0.2, 0.2, 0.25), "horn": true, "star": true, "eye": Color(1, 0.3, 0.1), "scale": 1.7},
	"armorsaurus": {"kind": "quadruped", "color": Color(0.45, 0.42, 0.3), "armored": true, "eye": Color(1, 0.2, 0.1), "scale": 1.3},
	"veldora_dragon": {"kind": "dragon", "color": Color(0.12, 0.12, 0.18), "scale": 0.8},
	"salamander": {"kind": "serpent", "color": Color(1.0, 0.4, 0.1), "glow": 1.5, "scale": 0.55},
}

# ======================================================================= INIMIGOS
## attacks: padrões extras dos chefes (melee sempre existe).
## absorb_*: o que o Predador copia ao devorar o corpo.
const ENEMIES := {
	"serpent": {"name": "Serpente Tempestade", "model": {"kind": "serpent"}, "hp": 120.0, "speed": 3.2, "damage": 14.0, "aggro": 13.0, "range": 2.6, "exp": 20, "absorb_skill": "poison_breath"},
	"spider": {"name": "Aranha Negra", "model": {"kind": "spider"}, "hp": 70.0, "speed": 4.5, "damage": 9.0, "aggro": 14.0, "range": 2.0, "exp": 12, "absorb_skill": "sticky_thread"},
	"bat": {"name": "Morcego Gigante", "model": {"kind": "bat"}, "hp": 50.0, "speed": 5.5, "damage": 7.0, "aggro": 16.0, "range": 1.8, "exp": 10, "absorb_skill": "ultrasound", "absorb_form": "bat", "flying": true},
	"wolf": {"name": "Lobo Atroz", "model": {"kind": "quadruped", "color": Color(0.35, 0.35, 0.4), "star": true}, "hp": 140.0, "speed": 6.0, "damage": 16.0, "aggro": 18.0, "range": 2.4, "exp": 22, "absorb_skill": "shadow_motion"},
	"lizard": {"name": "Armadurossauro", "model": {"kind": "lizard"}, "hp": 90.0, "speed": 3.5, "damage": 11.0, "aggro": 12.0, "range": 2.2, "exp": 15, "absorb_skill": "body_armor"},
	"centipede": {"name": "Centopeia Maligna", "model": {"kind": "centipede"}, "hp": 100.0, "speed": 4.0, "damage": 12.0, "aggro": 13.0, "range": 2.2, "exp": 18, "absorb_skill": "paralyze_breath"},
	"boar": {"name": "Javali Selvagem", "model_id": "boar", "hp": 160.0, "speed": 5.5, "damage": 15.0, "aggro": 14.0, "range": 2.4, "exp": 25},
	"direwolf": {"name": "Lobo Atroz", "model_id": "direwolf", "hp": 140.0, "speed": 6.5, "damage": 14.0, "aggro": 30.0, "range": 2.4, "exp": 22, "absorb_skill": "shadow_motion"},
	"direwolf_leader": {"name": "Líder dos Lobos Atrozes", "model_id": "direwolf_leader", "boss": true, "hp": 700.0, "speed": 7.5, "damage": 24.0, "aggro": 40.0, "range": 3.5, "exp": 150, "absorb_form": "wolf",
		"attacks": [{"type": "dash", "dmg": 28.0, "cd": 4.0}, {"type": "summon", "enemy": "direwolf", "n": 2, "cd": 14.0}]},
	"armorsaurus": {"name": "Armadurossauro das Minas", "model_id": "armorsaurus", "hp": 260.0, "speed": 3.5, "damage": 18.0, "aggro": 16.0, "range": 3.0, "exp": 40, "absorb_skill": "body_armor"},
	"salamander": {"name": "Salamandra", "model_id": "salamander", "hp": 90.0, "speed": 5.0, "damage": 14.0, "aggro": 30.0, "range": 2.0, "exp": 15},
	"ifrit": {"name": "Ifrit, o Espírito do Fogo", "model_id": "ifrit", "boss": true, "hp": 1400.0, "speed": 4.5, "damage": 26.0, "aggro": 50.0, "range": 3.0, "exp": 400, "absorb_form": "human", "absorb_skill": "flame_control", "proj_color": Color(1.0, 0.5, 0.1),
		"attacks": [{"type": "volley", "n": 5, "spread": 0.6, "dmg": 16.0, "cd": 3.0, "speed": 18.0, "color": Color(1.0, 0.45, 0.1)}, {"type": "rain", "n": 5, "r": 3.0, "dmg": 28.0, "delay": 1.1, "cd": 6.0, "color": Color(1.0, 0.4, 0.1)}, {"type": "summon", "enemy": "salamander", "n": 3, "cd": 15.0}]},
	"ogre": {"name": "Ogro Guerreiro", "model_id": "ogre", "hp": 260.0, "speed": 5.0, "damage": 20.0, "aggro": 30.0, "range": 2.8, "exp": 45},
	"ogre_prince": {"name": "Jovem Mestre Ogro", "model_id": "ogre_prince", "boss": true, "hp": 1800.0, "speed": 6.5, "damage": 30.0, "aggro": 50.0, "range": 3.0, "exp": 500,
		"attacks": [{"type": "dash", "dmg": 32.0, "cd": 3.5}, {"type": "slam", "r": 6.0, "dmg": 35.0, "delay": 0.9, "cd": 6.0, "color": Color(0.2, 0.05, 0.05)}, {"type": "volley", "n": 3, "spread": 0.4, "dmg": 18.0, "cd": 4.0, "speed": 20.0, "color": Color(0.3, 0.05, 0.05)}]},
	"gabiru": {"name": "Gabiru, o Homem-Lagarto", "model_id": "gabiru", "boss": true, "hp": 1200.0, "speed": 6.0, "damage": 24.0, "aggro": 40.0, "range": 3.2, "exp": 300,
		"attacks": [{"type": "dash", "dmg": 26.0, "cd": 3.0}, {"type": "volley", "n": 1, "spread": 0.0, "dmg": 30.0, "cd": 4.0, "speed": 22.0, "color": Color(0.3, 0.8, 1.0)}]},
	"lizardman": {"name": "Homem-Lagarto", "model_id": "lizardman", "hp": 200.0, "speed": 5.0, "damage": 16.0, "aggro": 25.0, "range": 2.8, "exp": 30},
	"orc": {"name": "Orc", "model_id": "orc", "hp": 220.0, "speed": 4.5, "damage": 18.0, "aggro": 30.0, "range": 2.6, "exp": 35},
	"orc_knight": {"name": "Cavaleiro Orc", "model_id": "orc_knight", "hp": 420.0, "speed": 4.0, "damage": 26.0, "aggro": 30.0, "range": 3.0, "exp": 70},
	"geld": {"name": "Geld, o Lorde Orc (Orc Disaster)", "model_id": "geld", "boss": true, "hp": 4200.0, "speed": 5.0, "damage": 38.0, "aggro": 60.0, "range": 3.8, "exp": 1200, "absorb_skill": "starved", "regen": 12.0,
		"attacks": [{"type": "slam", "r": 7.0, "dmg": 45.0, "delay": 1.0, "cd": 5.0, "color": Color(0.6, 0.5, 0.1)}, {"type": "summon", "enemy": "orc", "n": 3, "cd": 12.0}, {"type": "rain", "n": 6, "r": 3.0, "dmg": 30.0, "delay": 1.2, "cd": 7.0, "color": Color(0.5, 0.4, 0.05)}, {"type": "dash", "dmg": 40.0, "cd": 5.0}]},
	"milim": {"name": "Milim Nava, a Destruidora", "model_id": "milim", "boss": true, "hp": 99999.0, "speed": 9.0, "damage": 30.0, "aggro": 80.0, "range": 2.6, "exp": 0, "invulnerable": true,
		"attacks": [{"type": "dash", "dmg": 30.0, "cd": 2.5}, {"type": "beam", "dmg": 45.0, "delay": 1.2, "cd": 7.0, "len": 40.0, "w": 3.0, "color": Color(1.0, 0.4, 0.7)}, {"type": "slam", "r": 8.0, "dmg": 35.0, "delay": 1.0, "cd": 6.0, "color": Color(1.0, 0.3, 0.6)}]},
	"falmuth_soldier": {"name": "Soldado de Falmuth", "model_id": "soldier", "hp": 300.0, "speed": 4.8, "damage": 22.0, "aggro": 40.0, "range": 2.6, "exp": 40},
	"falmuth_knight": {"name": "Cavaleiro Templário", "model_id": "knight", "hp": 600.0, "speed": 4.5, "damage": 30.0, "aggro": 40.0, "range": 3.2, "exp": 80},
	"falmuth_mage": {"name": "Mago de Falmuth", "model_id": "mage", "hp": 240.0, "speed": 4.0, "damage": 20.0, "aggro": 40.0, "range": 18.0, "exp": 50, "ranged": true, "proj_color": Color(0.6, 0.3, 1.0)},
	"shogo": {"name": "Shogo Taguchi (Otherworlder)", "model_id": "shogo", "boss": true, "hp": 5000.0, "speed": 7.0, "damage": 40.0, "aggro": 60.0, "range": 3.0, "exp": 2000, "regen": 20.0,
		"attacks": [{"type": "dash", "dmg": 40.0, "cd": 3.0}, {"type": "slam", "r": 6.0, "dmg": 45.0, "delay": 0.8, "cd": 5.0, "color": Color(0.8, 0.2, 0.1)}, {"type": "summon", "enemy": "falmuth_knight", "n": 2, "cd": 15.0}]},
	"clayman": {"name": "Clayman, o Lorde Demônio Marionetista", "model_id": "clayman", "boss": true, "hp": 9000.0, "speed": 6.0, "damage": 45.0, "aggro": 80.0, "range": 3.0, "exp": 5000,
		"attacks": [{"type": "volley", "n": 7, "spread": 0.9, "dmg": 30.0, "cd": 3.0, "speed": 20.0, "color": Color(0.7, 0.2, 0.9)}, {"type": "summon", "enemy": "marionette", "n": 3, "cd": 10.0}, {"type": "rain", "n": 6, "r": 3.5, "dmg": 45.0, "delay": 1.0, "cd": 6.0, "color": Color(0.6, 0.1, 0.8)}, {"type": "beam", "dmg": 60.0, "delay": 1.0, "cd": 9.0, "len": 35.0, "w": 2.5, "color": Color(0.8, 0.2, 1.0)}]},
	"marionette": {"name": "Marionete", "model_id": "marionette", "hp": 400.0, "speed": 6.0, "damage": 25.0, "aggro": 60.0, "range": 2.4, "exp": 40},
	"hinata": {"name": "Hinata Sakaguchi, Capitã dos Cavaleiros Sagrados", "model_id": "hinata", "boss": true, "hp": 12000.0, "speed": 8.5, "damage": 50.0, "aggro": 80.0, "range": 3.0, "exp": 8000,
		"attacks": [{"type": "dash", "dmg": 55.0, "cd": 2.5}, {"type": "beam", "dmg": 80.0, "delay": 1.3, "cd": 8.0, "len": 45.0, "w": 3.0, "color": Color(0.9, 0.95, 1.0)}, {"type": "rain", "n": 8, "r": 3.0, "dmg": 50.0, "delay": 1.2, "cd": 7.0, "color": Color(0.85, 0.9, 1.0)}, {"type": "volley", "n": 5, "spread": 0.5, "dmg": 35.0, "cd": 3.5, "speed": 26.0, "color": Color(0.9, 0.95, 1.0)}]},
	"imperial_soldier": {"name": "Soldado do Império Oriental", "model_id": "imperial", "hp": 700.0, "speed": 5.0, "damage": 32.0, "aggro": 45.0, "range": 16.0, "exp": 90, "ranged": true, "proj_color": Color(1.0, 0.9, 0.5)},
	"magic_tank": {"name": "Tanque Mágico Imperial", "model_id": "magic_tank", "hp": 2500.0, "speed": 2.5, "damage": 50.0, "aggro": 50.0, "range": 28.0, "exp": 300, "ranged": true, "proj_color": Color(1.0, 0.4, 0.2), "big": true},
	"kondo": {"name": "Tenente-Coronel Kondo Tatsuya", "model_id": "kondo", "boss": true, "hp": 16000.0, "speed": 7.0, "damage": 55.0, "aggro": 80.0, "range": 20.0, "exp": 12000, "ranged": true, "proj_color": Color(1.0, 0.95, 0.6),
		"attacks": [{"type": "volley", "n": 9, "spread": 0.8, "dmg": 40.0, "cd": 2.5, "speed": 34.0, "color": Color(1.0, 0.95, 0.6)}, {"type": "rain", "n": 8, "r": 3.0, "dmg": 55.0, "delay": 1.0, "cd": 6.0, "color": Color(1.0, 0.8, 0.3)}, {"type": "summon", "enemy": "imperial_soldier", "n": 3, "cd": 14.0}]},
	"yuuki": {"name": "Yuuki Kagurazaka, o Imperador das Sombras", "model_id": "yuuki", "boss": true, "hp": 22000.0, "speed": 9.0, "damage": 65.0, "aggro": 90.0, "range": 3.0, "exp": 20000, "regen": 30.0,
		"attacks": [{"type": "dash", "dmg": 60.0, "cd": 2.0}, {"type": "slam", "r": 8.0, "dmg": 70.0, "delay": 0.9, "cd": 5.0, "color": Color(0.5, 0.0, 0.2)}, {"type": "beam", "dmg": 90.0, "delay": 1.1, "cd": 7.0, "len": 45.0, "w": 3.5, "color": Color(0.6, 0.0, 0.3)}, {"type": "rain", "n": 10, "r": 3.0, "dmg": 60.0, "delay": 1.0, "cd": 8.0, "color": Color(0.4, 0.0, 0.3)}]},
	"veldora_spar": {"name": "Veldora (Treino)", "model_id": "veldora_dragon", "boss": true, "hp": 30000.0, "speed": 5.0, "damage": 60.0, "aggro": 90.0, "range": 6.0, "exp": 15000, "big": true,
		"attacks": [{"type": "beam", "dmg": 80.0, "delay": 1.2, "cd": 6.0, "len": 45.0, "w": 4.0, "color": Color(0.3, 0.2, 0.6)}, {"type": "rain", "n": 10, "r": 3.5, "dmg": 60.0, "delay": 1.2, "cd": 7.0, "color": Color(0.2, 0.2, 0.5)}, {"type": "slam", "r": 10.0, "dmg": 70.0, "delay": 1.0, "cd": 5.0, "color": Color(0.3, 0.3, 0.7)}]},
}

# ======================================================================= ALIADOS (grupo)
## special: habilidade que o aliado usa sozinho de tempos em tempos.
const ALLIES := {
	"ranga": {"hp": 500.0, "dmg": 22.0, "speed": 11.0, "range": 2.6, "special": {"name": "Raio Negro", "type": "lightning", "dmg": 70.0, "cd": 7.0}},
	"gobta": {"hp": 300.0, "dmg": 14.0, "speed": 8.0, "range": 2.2, "special": {"name": "Ataque Sorrateiro", "type": "dash", "dmg": 40.0, "cd": 6.0}},
	"benimaru": {"hp": 900.0, "dmg": 40.0, "speed": 9.0, "range": 2.8, "special": {"name": "Hell Flare", "type": "flare", "dmg": 160.0, "cd": 10.0}},
	"shion": {"hp": 1100.0, "dmg": 48.0, "speed": 8.5, "range": 3.2, "special": {"name": "Golpe Esmagador", "type": "slam", "dmg": 130.0, "cd": 8.0}},
	"souei": {"hp": 700.0, "dmg": 34.0, "speed": 11.0, "range": 2.4, "special": {"name": "Fio de Aço Sombrio", "type": "root", "dmg": 60.0, "cd": 7.0}},
	"hakurou": {"hp": 750.0, "dmg": 45.0, "speed": 10.0, "range": 2.8, "special": {"name": "Corte Instantâneo", "type": "dash", "dmg": 140.0, "cd": 6.0}},
	"shuna": {"hp": 600.0, "dmg": 20.0, "speed": 8.0, "range": 14.0, "ranged": true, "proj_color": Color(1.0, 0.7, 0.85), "special": {"name": "Cura Sagrada", "type": "heal", "amount": 0.3, "cd": 12.0}},
	"gabiru": {"hp": 800.0, "dmg": 32.0, "speed": 9.0, "range": 3.0, "special": {"name": "Lança Vórtice", "type": "slam", "dmg": 90.0, "cd": 8.0}},
	"geld_new": {"hp": 1600.0, "dmg": 36.0, "speed": 7.0, "range": 3.0, "special": {"name": "Escudo de Gula", "type": "taunt", "dmg": 60.0, "cd": 10.0}},
	"diablo": {"hp": 2500.0, "dmg": 80.0, "speed": 11.0, "range": 3.0, "special": {"name": "Tentação: Mundo de Ilusão", "type": "stun_all", "dmg": 200.0, "cd": 12.0}},
	"milim": {"hp": 5000.0, "dmg": 120.0, "speed": 12.0, "range": 2.6, "special": {"name": "Drago Nova", "type": "flare", "dmg": 500.0, "cd": 14.0}},
}

# ======================================================================= PERSONAGENS (NPCs, aliados e Enciclopédia)
const CHARS := {
	"rimuru": {"name": "Rimuru Tempest", "info": "Satoru Mikami reencarnado como slime. Fundador da Federação Jura Tempest, depois Lorde Demônio e um dos Octagrama (Oito Estrelas Lordes Demônio). Habilidades: Predador -> Belzebu, Grande Sábio -> Raphael -> Ciel."},
	"veldora": {"name": "Veldora Tempest", "model": "veldora_human", "info": "Dragão da Tempestade, um dos quatro Verdadeiros Dragões. Selado por 300 anos pela heroína Chloe/Hero. Amigo de Rimuru e fã de mangá.", "lines": ["KUAHAHAHA! Este mangá que você me deu é uma obra-prima, Rimuru!", "Quer treinar comigo? Não vou pegar leve! (Fale de novo para lutar)", "Ser chamado de 'tio Veldora' pelas crianças não é nada mal..."]},
	"great_sage": {"name": "Grande Sábio", "info": "Habilidade única de Rimuru. Evoluiu para Raphael (Senhor da Sabedoria) e depois ganhou consciência como Ciel."},
	"ranga": {"name": "Ranga", "model": "ranga", "info": "Filho do líder dos Lobos Atrozes. Recebeu o nome de Rimuru e evoluiu para Lobo Estelar Tempest. Vive na sombra do mestre.", "lines": ["Mestre! Pode contar comigo!", "Vou proteger o Mestre de dentro da sua sombra!"]},
	"gobta": {"name": "Gobta", "model": "gobta", "info": "Hobgoblin desastrado e preguiçoso, mas genial em batalha. Líder dos Cavaleiros Goblin, montados em lobos.", "lines": ["Eu nem tava dormindo, chefe! Juro!", "O mestre Hakurou vai me matar de tanto treinar..."]},
	"rigurd": {"name": "Rigurd", "model": "rigurd", "info": "Ancião da vila goblin que virou um hobgoblin musculoso após ser nomeado. Cuida da administração de Tempest.", "lines": ["Rimuru-sama! A vila nunca esteve tão bem!", "Os lobos e os goblins vivem em harmonia graças ao senhor!"]},
	"rigur": {"name": "Rigur", "info": "Filho de Rigurd e chefe da guarda goblin. Herdou o nome do irmão que morreu protegendo a vila."},
	"kaijin": {"name": "Kaijin", "model": "kaijin", "info": "Ferreiro anão exilado de Dwargon junto com Rimuru. Forja as armas de Tempest com Kurobe.", "lines": ["Essa katana saiu perfeita! Kurobe é um gênio.", "Saudades do bar das elfas em Dwargon... hehe."]},
	"dwarf": {"name": "Irmãos Garm, Dold e Mildo", "model": "dwarf", "info": "Artesãos anões: Garm faz armaduras, Dold é artesão fino e Mildo é arquiteto. Construíram a cidade de Tempest.", "lines": ["Mildo projetou essas casas em uma noite!", "Com magículas e trabalho duro, qualquer prédio fica de pé!"]},
	"gazel": {"name": "Gazel Dwargo", "model": "gazel", "info": "Rei Herói dos anões e discípulo de Hakurou. Exilou Rimuru para protegê-lo e depois assinou aliança com Tempest.", "lines": ["Um rei deve sempre pensar no seu povo, Rimuru.", "Seu crescimento é assustador, slime."]},
	"vester": {"name": "Vester", "info": "Ministro anão que armou contra Kaijin. Depois se arrependeu e foi pesquisar em Tempest."},
	"shizu": {"name": "Shizue Izawa (Shizu)", "model": "shizu", "info": "Japonesa invocada durante a 2ª Guerra. Possuída pelo espírito Ifrit, virou a heroína 'Chama Eterna'. Rimuru herdou sua forma e sua vontade.", "lines": ["Você também é do Japão, não é? Que saudade de casa...", "Por favor... salve aquelas crianças..."]},
	"kabal": {"name": "Kabal", "model": "kabal", "info": "Líder do grupo de aventureiros de Blumund (Kabal, Eren e Gido).", "lines": ["Ei, slime! Valeu por salvar a gente!"]},
	"eren": {"name": "Eren", "model": "eren", "info": "Maga do grupo de Kabal. Na verdade é filha de nobres do Reino Mágico Thalion.", "lines": ["Esse slime é fofo demais!"]},
	"gido": {"name": "Gido", "model": "gido", "info": "Ladrão do grupo de Kabal.", "lines": ["Shhh... estamos em missão!"]},
	"benimaru": {"name": "Benimaru", "model": "benimaru", "info": "Ex-príncipe ogro, agora Kijin e Comandante Supremo das forças de Tempest. Mestre das chamas negras (Hell Flare).", "lines": ["Minhas chamas existem para proteger Tempest.", "Rimuru-sama, as tropas estão prontas."]},
	"shuna": {"name": "Shuna", "model": "shuna", "info": "Irmã de Benimaru, sacerdotisa Kijin. Costura, cozinha, cura e analisa magias. Também protege Rimuru... de Shion.", "lines": ["Fiz roupas novas para o senhor, Rimuru-sama!", "Por favor, não deixe a Shion cozinhar..."]},
	"shion": {"name": "Shion", "model": "shion", "info": "Kijin secretária e guarda-costas de Rimuru. Força absurda e comida venenosa. Morreu no ataque de Falmuth e foi revivida.", "lines": ["Eu protejo Rimuru-sama! Ninguém encosta nele!", "Fiz um ensopado especial! ...Por que todos estão correndo?"]},
	"souei": {"name": "Souei", "model": "souei", "info": "Kijin espião, mestre de fios e clones. Comanda a inteligência de Tempest.", "lines": ["Relatório: nenhuma ameaça num raio de 10 km.", "..."]},
	"hakurou": {"name": "Hakurou", "model": "hakurou", "info": "Velho mestre espadachim Kijin. Instrutor de Gobta, de Benimaru e até do Rei Gazel.", "lines": ["Hohoho. Seu corte ainda está lento, Gobta.", "A espada deve ser uma extensão do coração."]},
	"kurobe": {"name": "Kurobe", "model": "kurobe", "info": "Ferreiro Kijin. Forjou a katana de Rimuru e trabalha com Kaijin.", "lines": ["Essa lâmina tem magículas do mestre... é especial."]},
	"gabiru": {"name": "Gabiru", "model": "gabiru", "info": "Homem-lagarto convencido que ganhou nome de Gelmud. Depois virou Dragonewt e líder dos Hiryuu de Tempest.", "lines": ["Eu, Gabiru, sou o grande guerreiro do pântano!", "Rimuru-sama! Admire minha nova lança Vórtice!"]},
	"souka": {"name": "Souka", "info": "Irmã de Gabiru e guarda pessoal de Souei."},
	"treyni": {"name": "Treyni", "model": "treyni", "info": "Dríade guardiã da Grande Floresta de Jura. Pediu a Rimuru para derrotar o Lorde Orc.", "lines": ["A Floresta de Jura agradece a você, Rimuru Tempest.", "As árvores sussurram sobre um grande perigo..."]},
	"geld": {"name": "Geld (Orc Disaster)", "info": "Lorde Orc que, faminto, devorou o próprio rei para salvar seu povo. Devorado por Rimuru, que carregou seus pecados."},
	"geld_new": {"name": "Geld (Novo)", "model": "geld_new", "info": "Filho do antigo general orc. Recebeu o nome Geld e lidera os Orcs Altos na construção de estradas.", "lines": ["Meu povo deve a vida a Rimuru-sama. Vamos trabalhar dobrado!"]},
	"gelmud": {"name": "Gelmud", "info": "Majin a serviço de Clayman que dava nomes a monstros para criar um Lorde Demônio fantoche. Devorado pelo Lorde Orc."},
	"milim": {"name": "Milim Nava", "model": "milim", "info": "Lorde Demônio 'Destruidora', filha do Verdadeiro Dragão Veldanava. Melhor amiga de Rimuru depois do mel.", "lines": ["Rimuru! Brinca comigo! Wahaha!", "Esse mel é a melhor coisa do mundo!"]},
	"carillon": {"name": "Carillon", "model": "carillon", "info": "Lorde Demônio Rei Leão, líder do Reino Bestial Eurazania. Depois serviu Milim.", "lines": ["Hah! Você tem coragem, slime."]},
	"frey": {"name": "Frey", "model": "frey", "info": "Lorde Demônio Rainha Harpia. Abdicou para servir Milim.", "lines": ["Que interessante... um slime Lorde Demônio."]},
	"clayman": {"name": "Clayman", "info": "Lorde Demônio Marionetista, membro dos Moderate Harlequin. Armou o ataque a Tempest. Derrotado por Rimuru na Walpurgis."},
	"laplace": {"name": "Laplace", "info": "Palhaço dos Moderate Harlequin, aliado de Clayman e de Yuuki."},
	"guy": {"name": "Guy Crimson", "model": "guy", "info": "O Lorde Demônio mais antigo e mais forte, 'Senhor das Trevas'. Primordial Vermelho.", "lines": ["Hmm. Você é divertido, Rimuru.", "Não decepcione a mesa dos Lordes Demônio."]},
	"leon": {"name": "Leon Cromwell", "model": "leon", "info": "Lorde Demônio Platinado. Invocou Shizu para o mundo... Rimuru jurou dar um soco nele.", "lines": ["...Shizu? Sim, eu a invoquei. Não foi intencional."]},
	"luminous": {"name": "Luminous Valentine", "model": "luminous", "info": "Lorde Demônio rainha vampira e deusa secreta da Igreja Ocidental. Patroa da Hinata.", "lines": ["Não toque nos meus súditos, slime."]},
	"ramiris": {"name": "Ramiris", "model": "ramiris", "info": "Lorde Demônio fada, mãe dos espíritos. Fofa e barulhenta. Mudou seu Labirinto para Tempest.", "lines": ["Eu sou uma Lorde Demônio! Não me chame de fadinha!", "Meu Labirinto deixa Tempest invencível!"]},
	"dagruel": {"name": "Dagruel", "model": "dagruel", "info": "Lorde Demônio gigante, guardião do selo de Veldanava.", "lines": ["Hahaha! Um banquete divertido este ano!"]},
	"deeno": {"name": "Deeno", "model": "deeno", "info": "Lorde Demônio anjo caído, o mais preguiçoso. Depois virou espião dos inimigos.", "lines": ["Zzz... ah, acabou a reunião?"]},
	"diablo": {"name": "Diablo", "model": "diablo", "info": "Primordial Negro (Noir) invocado por Rimuru no Festival da Colheita. Mordomo absurdamente leal e poderoso.", "lines": ["Kufufufu... Rimuru-sama, deseje e eu farei.", "Quem ousa desrespeitar meu mestre?"]},
	"testarossa": {"name": "Testarossa, Ultima e Carrera", "info": "Primordiais Branca, Violeta e Amarela trazidas por Diablo. Viraram generais de Tempest (Testarossa é a diplomata)."},
	"hinata": {"name": "Hinata Sakaguchi", "model": "hinata", "info": "Capitã dos Cavaleiros Sagrados da Igreja Ocidental e aluna de Shizu. Achou que Rimuru matou Shizu. Depois virou aliada.", "lines": ["Eu errei sobre você, Rimuru. Desculpe.", "A Shizu-sensei estaria orgulhosa de você."]},
	"yuuki": {"name": "Yuuki Kagurazaka", "info": "Japonês, Grande Mestre da Guilda e aluno de Shizu. Na verdade é o líder secreto dos Moderate Harlequin e quer dominar o mundo."},
	"chloe": {"name": "Chloe Aubert", "model": "chloe", "info": "Uma das crianças de Shizu. Ela é a Heroína que selou Veldora, voltando no tempo várias vezes.", "lines": ["Sensei Rimuru! Brinca de herói com a gente!"]},
	"kids": {"name": "Kenya, Ryota, Gale e Alice", "model": "kids", "info": "Crianças de outro mundo da escola de Ingrassia, salvas por Rimuru do colapso de magículas.", "lines": ["Sensei! Olha o que a gente aprendeu!"]},
	"folgen": {"name": "Folgen", "info": "Capitão dos cavaleiros de Falmuth no ataque a Tempest."},
	"shogo": {"name": "Shogo Taguchi", "info": "Otherworlder de Falmuth que matou moradores de Tempest. Foi devorado por Rimuru."},
	"kyoya": {"name": "Kyoya Tachibana", "info": "Otherworlder arrogante de Falmuth. Derrotado por Benimaru... digo, por Shion revivida no mangá."},
	"edmaris": {"name": "Edmaris", "info": "Rei de Falmuth que ordenou o ataque. Perdeu tudo e abdicou para Youm."},
	"youm": {"name": "Youm", "info": "Aventureiro que virou herói e depois rei do novo Reino de Farmenas, aliado de Tempest."},
	"mjurran": {"name": "Mjurran", "info": "Bruxa a serviço de Clayman que se uniu a Youm."},
	"elmesia": {"name": "Elmesia El-Ru Sarion", "model": "elmesia", "info": "Imperatriz élfica de Sarion. Vem ao Festival dos Fundadores de Tempest.", "lines": ["Tempest é um país tão divertido!"]},
	"mjollmile": {"name": "Mjöllmile", "info": "Mercador humano de Blumund e organizador do Festival dos Fundadores."},
	"kondo": {"name": "Kondo Tatsuya", "info": "Tenente-coronel do Império Oriental, japonês da era Taishō, atirador com a habilidade Juiz."},
	"masayuki": {"name": "Masayuki Honjo", "info": "'Herói' japonês de sorte absurda. Depois virou o Imperador Rudra reencarnado."},
	"veldanava": {"name": "Veldanava", "info": "O Verdadeiro Dragão Estelar, criador do mundo e pai de Milim."},
	"zegion": {"name": "Zegion e Apito", "info": "Insetos salvos por Veldora/Rimuru. Zegion vira um dos guardiões mais fortes do Labirinto."},
	"adalmann": {"name": "Adalmann", "info": "Lich sacerdote que se junta a Tempest com seu dragão morto-vivo."},
}

# ======================================================================= LORE
const LORE := [
	["Federação Jura Tempest", "Nação de monstros fundada por Rimuru na Grande Floresta de Jura. Capital: Rimuru. Aliada de Dwargon, Blumund e Farmenas."],
	["Aliança da Floresta de Jura", "Pacto entre Tempest, Homens-Lagarto, Orcs Altos, Dríades e as raças da floresta após a derrota do Lorde Orc."],
	["Nomeação", "Dar nome a um monstro gasta magículas e o faz evoluir. Goblins viram Hobgoblins, Ogros viram Kijin, Lobos Atrozes viram Lobos Estelares Tempest."],
	["Festival da Colheita", "Ritual para virar Lorde Demônio Verdadeiro: é preciso as almas de 10.000 humanos. Rimuru usou Megiddo contra o exército de Falmuth."],
	["Walpurgis", "O Banquete dos Lordes Demônio. Ali Rimuru derrotou Clayman e os Lordes viraram os Octagrama (Oito Estrelas)."],
	["Octagrama", "Guy Crimson, Milim Nava, Ramiris, Dagruel, Leon Cromwell, Luminous Valentine, Deeno e Rimuru Tempest."],
	["Os Quatro Verdadeiros Dragões", "Veldanava (Estelar), Velgrynd (Chama Ardente), Velzard (Congelante) e Veldora (Tempestade)."],
	["Moderate Harlequin", "Organização de palhaços (Laplace, Footman, Tear, Kazalim) por trás de muitas tragédias, liderada em segredo por Yuuki."],
	["Igreja Ocidental (Luminismo)", "Religião que prega que monstros são inimigos. Seus Cavaleiros Sagrados são liderados por Hinata."],
	["Império Oriental (Nasca)", "Superpotência do Leste governada pelo Imperador Rudra. Invadiu Tempest com quase 1 milhão de soldados."],
	["Skills Únicas e Supremas", "Rimuru: Predador->Gula->Belzebu; Grande Sábio->Raphael->Ciel. Skills Supremas (Ultimate) são o ápice do poder."],
	["Labirinto de Ramiris", "Dungeon de 100 andares sob Tempest. Quem morre lá dentro revive. Veldora é o chefe final."],
]

# ======================================================================= ÁREAS
## spawns: [tipo, quantidade, centro, espalhamento, capítulo_min, capítulo_max]
## npcs: [id, posição, capítulo_min, capítulo_max]
## portals: [área_destino, posição, capítulo_min, nome]
const AREAS := {
	"cave": {"name": "Caverna Selada", "spawn": Vector3(0, 1, 14),
		"spawns": [["spider", 4, Vector3(-26, 0, -28), 5.0, 1, 99], ["bat", 4, Vector3(30, 0, -18), 5.0, 1, 99], ["serpent", 2, Vector3(26, 0, 28), 5.0, 1, 99],
			["wolf", 3, Vector3(-26, 0, 32), 5.0, 1, 99], ["lizard", 2, Vector3(18, 0, -2), 5.0, 1, 99], ["lizard", 2, Vector3(-12, 0, -40), 5.0, 1, 99],
			["centipede", 2, Vector3(38, 0, 18), 4.0, 1, 99]],
		"npcs": [],
		"portals": [["forest", Vector3(0, 0, 50), 2, "Saída da Caverna"]]},
	"forest": {"name": "Grande Floresta de Jura", "spawn": Vector3(-52, 1, -112),
		"spawns": [["boar", 3, Vector3(60, 0, 40), 12.0, 2, 99], ["boar", 3, Vector3(-60, 0, 70), 12.0, 2, 99], ["spider", 3, Vector3(-30, 0, -90), 8.0, 2, 99],
			["lizardman", 3, Vector3(-110, 0, -95), 10.0, 7, 99], ["orc", 3, Vector3(100, 0, -20), 10.0, 7, 99]],
		"npcs": [["rigurd", Vector3(4, 0, -6), 2, 99], ["kaijin", Vector3(-12, 0, 8), 4, 99], ["dwarf", Vector3(-15, 0, 12), 4, 99],
			["kabal", Vector3(52, 0, -64), 4, 4], ["eren", Vector3(55, 0, -62), 4, 4], ["gido", Vector3(50, 0, -61), 4, 4], ["shizu", Vector3(60, 0, -60), 4, 4],
			["treyni", Vector3(-25, 0, 118), 6, 99], ["milim", Vector3(12, 0, 10), 8, 99], ["veldora", Vector3(0, 0, 18), 9, 99],
			["ramiris", Vector3(6, 0, 20), 10, 99], ["hinata", Vector3(-6, 0, 22), 11, 99], ["chloe", Vector3(16, 0, -10), 10, 99], ["kids", Vector3(18, 0, -12), 10, 99],
			["gazel", Vector3(-20, 0, -4), 11, 99], ["elmesia", Vector3(-22, 0, -8), 11, 99], ["geld_new", Vector3(24, 0, 6), 7, 99]],
		"portals": [["cave", Vector3(-55, 0, -125), 2, "Caverna Selada"], ["dwargon", Vector3(-140, 0, -10), 3, "Reino Anão Dwargon"],
			["falmuth", Vector3(10, 0, -140), 8, "Planícies de Falmuth"], ["walpurgis", Vector3(135, 0, -135), 9, "Walpurgis"]]},
	"dwargon": {"name": "Reino Anão Dwargon", "spawn": Vector3(0, 1, 40),
		"spawns": [["armorsaurus", 3, Vector3(45, 0, -40), 8.0, 3, 99]],
		"npcs": [["kaijin", Vector3(-10, 0, 0), 3, 3], ["dwarf", Vector3(-14, 0, 3), 3, 3], ["gazel", Vector3(0, 0, -35), 3, 99]],
		"portals": [["forest", Vector3(0, 0, 52), 3, "Floresta de Jura"]]},
	"falmuth": {"name": "Planícies de Falmuth", "spawn": Vector3(0, 1, 90),
		"spawns": [],
		"npcs": [],
		"portals": [["forest", Vector3(0, 0, 105), 8, "Voltar a Tempest"]]},
	"walpurgis": {"name": "Walpurgis — Salão dos Lordes Demônio", "spawn": Vector3(0, 1, 40),
		"spawns": [],
		"npcs": [["guy", Vector3(0, 0, -30), 9, 99], ["leon", Vector3(-14, 0, -24), 9, 99], ["luminous", Vector3(14, 0, -24), 9, 99], ["ramiris", Vector3(-20, 0, -14), 9, 9],
			["dagruel", Vector3(22, 0, -14), 9, 99], ["deeno", Vector3(-24, 0, -2), 9, 99], ["frey", Vector3(24, 0, -2), 9, 99], ["carillon", Vector3(26, 0, 6), 9, 99]],
		"portals": [["forest", Vector3(0, 0, 50), 9, "Voltar a Tempest"]]},
}

# ======================================================================= HISTÓRIA
## Passos executados em ordem. Tipos:
##  chapter  -> cartão de capítulo (n, title, sub)
##  dialog   -> falas [[quem, texto], ...]
##  sage     -> mensagem do Grande Sábio
##  obj      -> objetivo; kind: reach | talk | kill | boss | absorb | absorb_counts | survive | area
##  reward   -> skills, forms, allies, town, title, hp, mp, level
##  evolve   -> efeito visual de evolução
##  end      -> créditos (depois o jogo segue livre)
const STORY := [
	# ------------------------------------------------------------ Cap. 1
	{"t": "chapter", "n": 1, "title": "Reencarnado como Slime", "sub": "Arco da Caverna Selada"},
	{"t": "sage", "text": "Confirmação: reencarnação concluída. Habilidades únicas [Predador] e [Grande Sábio] adquiridas."},
	{"t": "sage", "text": "Notificação: uma aura gigantesca foi detectada ao norte."},
	{"t": "obj", "kind": "reach", "area": "cave", "pos": Vector3(0, 0, -20), "r": 15.0, "text": "Explore a Caverna Selada e encontre a origem da aura gigantesca (norte)."},
	{"t": "dialog", "lines": [
		["Veldora", "Consegue me ouvir, pequenino? KUAHAHAHA! Eu sou Veldora, o Dragão da Tempestade, um dos quatro Verdadeiros Dragões!"],
		["Slime", "(Um dragão gigante?! E eu sou só um slime...)"],
		["Veldora", "Fui selado aqui pela heroína com a Prisão Infinita há 300 anos. Estou entediado até a alma! Que tal sermos amigos?"],
		["Slime", "Amigos? ...Tá bom! Mas só se você não ficar com raiva se eu não voltar pra conversar."],
		["Veldora", "KUAHAHA! Então vamos trocar nomes! A partir de hoje você é RIMURU TEMPEST, e eu serei VELDORA TEMPEST!"],
		["Grande Sábio", "Proposta: devorar o Veldora com o Predador e analisar a Prisão Infinita por dentro. Porém, o Predador ainda é fraco demais."],
		["Grande Sábio", "Sugestão: devore 5 monstros e 6 Minérios Mágicos para aumentar a capacidade. A Erva Hipokute cura; a água do lago (oeste) ensina algo útil."]]},
	{"t": "reward", "title": "Rimuru Tempest", "mp": 30, "msg": "Você recebeu o nome \"Rimuru Tempest\". A quantidade de magículas aumentou!"},
	{"t": "obj", "kind": "absorb_counts", "area": "cave", "counts": {"monster": 5, "ore": 6}, "text": "Fortaleça o Predador: devore monstros derrotados e Minérios Mágicos."},
	{"t": "sage", "text": "Informe: condições satisfeitas! O Predador agora pode conter a Prisão Infinita. Volte ao Veldora."},
	{"t": "obj", "kind": "absorb", "area": "cave", "what": "veldora", "pos": Vector3(0, 0, -20), "text": "Volte ao Veldora e use o PREDADOR para devorá-lo junto com a Prisão Infinita."},
	{"t": "dialog", "lines": [
		["Grande Sábio", "Informe: Veldora e a Prisão Infinita foram armazenados no Estômago. Análise da Prisão Infinita iniciada em paralelo."],
		["Veldora", "(Da barriga do slime) KUAHAHAHA! Que lugar confortável! Conto com você, Rimuru!"],
		["Rimuru", "Agora é hora de sair desta caverna e conhecer o mundo... Quem sabe até fundar uma nação para monstros!"]]},
	{"t": "reward", "skills": ["magic_sense", "self_regen", "mimicry"], "hp": 20, "msg": "Habilidades adquiridas: Sentido Mágico, Autorregeneração e Mimetismo (troque de forma com o botão FORMA)."},
	# ------------------------------------------------------------ Cap. 2
	{"t": "chapter", "n": 2, "title": "A Vila Goblin", "sub": "Arco da Floresta de Jura"},
	{"t": "obj", "kind": "area", "area": "forest", "pos": Vector3(0, 0, 50), "text": "Saia da Caverna Selada (portal ao sul)."},
	{"t": "dialog", "lines": [
		["Rimuru", "Luz do sol! Ar fresco! A Grande Floresta de Jura..."],
		["Goblin", "Ó-ó poderoso monstro! Por favor, venha à nossa vila! Precisamos de ajuda!"]]},
	{"t": "obj", "kind": "talk", "npc": "rigurd", "area": "forest", "text": "Siga até a vila goblin no centro da floresta e fale com o ancião."},
	{"t": "dialog", "lines": [
		["Ancião Goblin", "Os Lobos Atrozes vão atacar esta noite. Nossos guerreiros morreram... e o deus-dragão Veldora sumiu, então os monstros estão agitados."],
		["Rimuru", "(Ops... essa parte do Veldora é culpa minha.) Tudo bem! Eu protejo a vila. Em troca, vocês me seguem."],
		["Ancião Goblin", "Obrigado, Rimuru-sama!"]]},
	{"t": "obj", "kind": "kill", "area": "forest", "enemy": "direwolf", "count": 8, "spawn": [["direwolf", 8, Vector3(30, 0, 30), 10.0]], "pos": Vector3(30, 0, 30), "text": "Defenda a vila: derrote os Lobos Atrozes."},
	{"t": "obj", "kind": "boss", "area": "forest", "enemy": "direwolf_leader", "spawn": [["direwolf_leader", 1, Vector3(35, 0, 35), 0.0]], "pos": Vector3(35, 0, 35), "text": "Derrote o Líder dos Lobos Atrozes!"},
	{"t": "obj", "kind": "absorb", "area": "forest", "what": "direwolf_leader", "text": "Devore o corpo do líder com o PREDADOR para copiar sua forma."},
	{"t": "dialog", "lines": [
		["Rimuru", "(Na forma de lobo) AUUUUU! Lobos! Sirvam a mim ou vão embora!"],
		["Filho do Líder", "Nós... juramos lealdade ao senhor!"],
		["Rimuru", "Então vou dar nomes a todos vocês! Você será RANGA. E o ancião será RIGURD. E você... GOBTA!"],
		["Grande Sábio", "Aviso: magículas esgotadas por nomear demais. Entrando em modo de baixo consumo..."],
		["Rigurd", "(Dias depois, musculoso) Rimuru-sama acordou! Todos nós evoluímos para Hobgoblins!"],
		["Ranga", "Mestre! Eu, Ranga, evoluí para Lobo Estelar Tempest! Leve-me com o senhor!"]]},
	{"t": "reward", "allies": ["ranga", "gobta"], "skills": ["black_lightning", "thought_accel"], "town": 1, "level": 1, "msg": "Ranga e Gobta entraram no grupo! Skills: Raio Negro e Aceleração de Pensamento. Abra o MENU para equipar."},
	# ------------------------------------------------------------ Cap. 3
	{"t": "chapter", "n": 3, "title": "O Reino Anão", "sub": "Arco de Dwargon"},
	{"t": "dialog", "lines": [
		["Rigurd", "Rimuru-sama, a vila precisa de casas, roupas e ferramentas. Os anões de Dwargon são os melhores artesãos!"],
		["Rimuru", "Então vamos para o Reino Anão! (O portal fica a oeste.)"]]},
	{"t": "obj", "kind": "area", "area": "dwargon", "pos": Vector3(-140, 0, -10), "text": "Viaje até o Reino Anão Dwargon (portal a oeste da floresta)."},
	{"t": "obj", "kind": "talk", "npc": "kaijin", "area": "dwargon", "text": "Encontre o ferreiro Kaijin na cidade."},
	{"t": "dialog", "lines": [
		["Kaijin", "Um slime falante? ...Escuta, o ministro Vester me deu uma encomenda impossível: 20 espadas longas, e sem minério mágico!"],
		["Rimuru", "Deixa comigo. Eu tenho minério mágico guardado no Estômago... e posso copiar as espadas também."],
		["Kaijin", "O QUÊ?! ...Mas os Armadurossauros estão bloqueando a mina. Ninguém consegue trabalhar."]]},
	{"t": "obj", "kind": "kill", "area": "dwargon", "enemy": "armorsaurus", "count": 3, "pos": Vector3(45, 0, -40), "text": "Limpe a mina: derrote 3 Armadurossauros (leste)."},
	{"t": "obj", "kind": "talk", "npc": "gazel", "area": "dwargon", "text": "Vá ao trono do Rei Gazel Dwargo (norte) para o julgamento."},
	{"t": "dialog", "lines": [
		["Gazel Dwargo", "Vester armou contra Kaijin e o slime. Mas uma briga no bar... não posso ignorar."],
		["Gazel Dwargo", "Kaijin, você está exilado. E você, slime... (Que aura assustadora.) Vá. Mas nos veremos de novo."],
		["Kaijin", "Hah! Exílio? Vou pra Tempest! Meus irmãos Garm, Dold e Mildo também vão!"]]},
	{"t": "reward", "town": 2, "hp": 30, "mp": 20, "msg": "Kaijin e os irmãos anões se mudaram para Tempest! A vila começou a virar cidade."},
	# ------------------------------------------------------------ Cap. 4
	{"t": "chapter", "n": 4, "title": "Shizu, a Chama Eterna", "sub": "Arco de Shizu"},
	{"t": "obj", "kind": "talk", "npc": "shizu", "area": "forest", "text": "Aventureiros chegaram à floresta (sudeste de Tempest). Vá falar com eles."},
	{"t": "dialog", "lines": [
		["Kabal", "Valeu por nos salvar das formigas gigantes, slime!"],
		["Shizu", "Você... também é japonês, não é? Faz tanto tempo que não como comida de casa..."],
		["Shizu", "Fui trazida para este mundo pelo Lorde Demônio Leon durante a guerra. Ele colocou o espírito Ifrit dentro de mim."],
		["Shizu", "Ah... não... ele está saindo! FUJAM!"],
		["Grande Sábio", "Alerta: espírito superior Ifrit detectado. Resistência a fogo... insuficiente. Use água e gelo!"]]},
	{"t": "obj", "kind": "boss", "area": "forest", "enemy": "ifrit", "spawn": [["ifrit", 1, Vector3(62, 0, -66), 0.0]], "pos": Vector3(62, 0, -66), "text": "Derrote Ifrit! (Lâmina d'Água funciona bem)"},
	{"t": "obj", "kind": "absorb", "area": "forest", "what": "ifrit", "text": "Use o PREDADOR para devorar Ifrit e libertar Shizu."},
	{"t": "dialog", "lines": [
		["Shizu", "(Fraca) Obrigada... Rimuru. Sinto que meu tempo acabou..."],
		["Shizu", "Posso pedir uma coisa? Me deixe descansar dentro de você... E se puder, salve aquelas crianças na escola..."],
		["Rimuru", "Eu prometo, Shizu-san. Vou carregar sua vontade."],
		["Grande Sábio", "Informe: Shizue Izawa foi devorada. Forma humana adquirida! Resistência a fogo e Manipulação de Chamas adquiridas."]]},
	{"t": "reward", "forms": ["human"], "skills": ["flame_control"], "hp": 40, "msg": "Nova forma: Humano! Troque com o botão FORMA. Sua máscara agora é a de Shizu."},
	# ------------------------------------------------------------ Cap. 5
	{"t": "chapter", "n": 5, "title": "Os Ogros", "sub": "Arco dos Kijin"},
	{"t": "dialog", "lines": [
		["Ranga", "Mestre! Seis ogros estão vindo do nordeste! Parecem furiosos!"],
		["Rimuru", "A vila deles foi destruída... devem achar que fomos nós. Vamos até lá."]]},
	{"t": "obj", "kind": "reach", "area": "forest", "pos": Vector3(105, 0, 100), "r": 25.0, "text": "Vá até a vila ogra destruída (nordeste)."},
	{"t": "dialog", "lines": [
		["Jovem Mestre Ogro", "Majin mascarado! Você trouxe os orcs que destruíram nossa vila! Vamos vingar nosso povo!"],
		["Rimuru", "Calma! Eu não tenho nada a ver com isso! ...Tá, parece que vou ter que provar lutando."]]},
	{"t": "obj", "kind": "boss", "area": "forest", "enemy": "ogre_prince", "spawn": [["ogre_prince", 1, Vector3(110, 0, 108), 0.0], ["ogre", 3, Vector3(104, 0, 112), 6.0]], "pos": Vector3(110, 0, 108), "text": "Derrote o Jovem Mestre Ogro!"},
	{"t": "dialog", "lines": [
		["Princesa Ogra", "Irmão, pare! Este não é nosso inimigo! A aura dele... não tem cheiro de orc."],
		["Jovem Mestre Ogro", "...Perdemos. Você é forte, majin. Peço desculpas."],
		["Rimuru", "Que tal vocês morarem em Tempest? Eu dou nomes a vocês: BENIMARU, SHUNA, SHION, SOUEI, HAKUROU e KUROBE!"],
		["Grande Sábio", "Informe: os Ogros evoluíram para KIJIN! Magículas consumidas... de novo. Desmaiando."],
		["Shion", "Rimuru-sama! Eu, Shion, serei sua secretária e guarda-costas!"],
		["Benimaru", "Juro minha espada ao senhor. E vou te ensinar minha técnica: Hell Flare."]]},
	{"t": "reward", "allies": ["benimaru", "shion", "shuna", "souei", "hakurou"], "skills": ["hell_flare"], "town": 3, "level": 1, "msg": "Os Kijin entraram para Tempest! Skill Hell Flare adquirida. Escolha 3 aliados no MENU > Grupo."},
	# ------------------------------------------------------------ Cap. 6
	{"t": "chapter", "n": 6, "title": "O Lorde Orc", "sub": "Arco do Orc Disaster"},
	{"t": "dialog", "lines": [
		["Souei", "Relatório: um exército de 200.000 orcs marcha pela floresta. Eles devoram tudo. Um Lorde Orc nasceu."],
		["Treyni", "Eu sou Treyni, dríade guardiã da floresta. Rimuru Tempest, peço que derrote o Lorde Orc."]]},
	{"t": "obj", "kind": "talk", "npc": "treyni", "area": "forest", "text": "Fale com a dríade Treyni na Grande Árvore (norte)."},
	{"t": "dialog", "lines": [
		["Treyni", "Os homens-lagarto do pântano (sudoeste) estão em perigo. Mas o filho do chefe, Gabiru, se rebelou..."],
		["Gabiru", "(Aparecendo) HA! Eu, Gabiru, sou o futuro chefe! Um slime não manda em mim! Duelo!"]]},
	{"t": "obj", "kind": "boss", "area": "forest", "enemy": "gabiru", "spawn": [["gabiru", 1, Vector3(-20, 0, 100), 0.0]], "pos": Vector3(-20, 0, 100), "text": "Vença o duelo contra Gabiru."},
	{"t": "dialog", "lines": [
		["Gabiru", "Impossível... perdi?! ...Mas os orcs estão atacando meu povo agora mesmo!"],
		["Rimuru", "Então para de drama e vamos salvar todo mundo. Benimaru, Shion, comigo!"]]},
	{"t": "obj", "kind": "kill", "area": "forest", "enemy": "orc", "count": 15, "spawn": [["orc", 10, Vector3(-110, 0, -95), 14.0], ["orc_knight", 3, Vector3(-120, 0, -100), 8.0], ["orc", 6, Vector3(-95, 0, -80), 10.0]], "pos": Vector3(-110, 0, -95), "text": "Defenda o pântano dos homens-lagarto: derrote 15 orcs (sudoeste)."},
	{"t": "dialog", "lines": [
		["Geld", "FOME... TANTA FOME... Eu vou devorar TUDO! Até você, slime!"],
		["Grande Sábio", "Análise: o Lorde Orc evoluiu para ORC DISASTER. Ele regenera rápido. Ataque sem parar."]]},
	{"t": "obj", "kind": "boss", "area": "forest", "enemy": "geld", "spawn": [["geld", 1, Vector3(-118, 0, -110), 0.0]], "pos": Vector3(-118, 0, -110), "text": "Derrote Geld, o Orc Disaster!"},
	{"t": "obj", "kind": "absorb", "area": "forest", "what": "geld", "text": "Devore Geld com o PREDADOR. Encerre a fome dele."},
	{"t": "dialog", "lines": [
		["Geld", "Meus irmãos... estão famintos... eu não posso... morrer..."],
		["Rimuru", "Eu vou carregar seus pecados. E os do seu povo também. Descanse."],
		["Geld", "...Obrigado. Que... banquete..."],
		["Grande Sábio", "Informe: skill única [Faminto] adquirida. Combinada com o Predador, ela vira [Gula]!"],
		["Rimuru", "A partir de hoje, orcs, homens-lagarto, goblins e dríades formam a ALIANÇA DA FLORESTA DE JURA!"],
		["Geld (novo)", "Eu herdarei o nome Geld. Os Orcs Altos vão construir as estradas de Tempest!"],
		["Gabiru", "Rimuru-sama! Eu, Gabiru, também quero servir ao senhor! Recebi o nome de novo e virei Dragonewt!"]]},
	{"t": "reward", "allies": ["gabiru", "geld_new"], "skills": ["starved"], "town": 4, "level": 2, "msg": "Aliança da Floresta de Jura formada! Gabiru e Geld no grupo. Skill: Faminto."},
	# ------------------------------------------------------------ Cap. 7
	{"t": "chapter", "n": 7, "title": "Milim Nava", "sub": "A Destruidora chega"},
	{"t": "dialog", "lines": [
		["???", "WAHAHAHA! Então você é o slime que derrotou o Lorde Orc?!"],
		["Milim", "Eu sou Milim Nava, Lorde Demônio! Vamos ver quem é o mais forte! Aguente 40 segundos!"],
		["Grande Sábio", "Aviso: diferença de poder incalculável. Sugestão: sobreviver. Não é possível vencer."]]},
	{"t": "obj", "kind": "survive", "area": "forest", "time": 40.0, "enemy": "milim", "spawn": [["milim", 1, Vector3(10, 0, 20), 0.0]], "pos": Vector3(10, 0, 20), "text": "Sobreviva à Milim por 40 segundos!"},
	{"t": "dialog", "lines": [
		["Rimuru", "(Ofegante) Espera, espera! Que tal... isso? É MEL!"],
		["Milim", "Mmm?! ...QUE DELÍCIA!!! Isso é trapaça, Rimuru!"],
		["Milim", "Tá decidido: a partir de hoje somos MELHORES AMIGOS! Vou morar aqui em Tempest! Wahaha!"],
		["Benimaru", "(Uma Lorde Demônio morando em casa... Que dor de cabeça.)"]]},
	{"t": "reward", "hp": 80, "mp": 50, "town": 4, "msg": "Milim agora é sua melhor amiga (ela fica na cidade). Vida e magículas máximas aumentaram!"},
	# ------------------------------------------------------------ Cap. 8
	{"t": "chapter", "n": 8, "title": "Tragédia e o Festival da Colheita", "sub": "Arco do Lorde Demônio"},
	{"t": "dialog", "lines": [
		["Rimuru", "(Voltando da escola de Ingrassia, onde salvou as crianças de Shizu.) ...Por que a cidade está em silêncio?"],
		["Benimaru", "Rimuru-sama... o Reino de Falmuth e a Igreja nos atacaram com uma barreira anti-magia. Muitos morreram."],
		["Benimaru", "A Shion... protegeu as crianças até o fim."],
		["Rimuru", "..."],
		["Grande Sábio", "Informe: existe uma chance de reviver os mortos. Condição: tornar-se um Lorde Demônio Verdadeiro através do Festival da Colheita."],
		["Rimuru", "Então eu vou me tornar um Lorde Demônio. O exército de Falmuth ainda está nas planícies. Vou sozinho."]]},
	{"t": "obj", "kind": "area", "area": "falmuth", "pos": Vector3(10, 0, -140), "text": "Vá às Planícies de Falmuth (portal ao sul da floresta)."},
	{"t": "obj", "kind": "kill", "area": "falmuth", "enemy": "falmuth_soldier", "count": 20, "spawn": [["falmuth_soldier", 12, Vector3(0, 0, 30), 18.0], ["falmuth_mage", 5, Vector3(0, 0, 10), 18.0], ["falmuth_knight", 4, Vector3(0, 0, 0), 15.0], ["falmuth_soldier", 10, Vector3(0, 0, -10), 18.0]], "pos": Vector3(0, 0, 20), "text": "Enfrente o exército de Falmuth: derrote 20 soldados."},
	{"t": "obj", "kind": "boss", "area": "falmuth", "enemy": "shogo", "spawn": [["shogo", 1, Vector3(0, 0, -20), 0.0]], "pos": Vector3(0, 0, -20), "text": "Derrote Shogo Taguchi, o Otherworlder que atacou Tempest."},
	{"t": "dialog", "lines": [
		["Rimuru", "Grande Sábio. Prepare a magia."],
		["Grande Sábio", "Entendido. Água vaporizada em lentes no céu... Ângulo do sol calculado. MAGIA MEGIDDO: ativada."],
		["Grande Sábio", "Informe: as condições para o Festival da Colheita foram cumpridas. Iniciando evolução para Lorde Demônio Verdadeiro..."]]},
	{"t": "evolve"},
	{"t": "dialog", "lines": [
		["Grande Sábio", "Informe: o Grande Sábio evoluiu para RAPHAEL, Senhor da Sabedoria."],
		["Raphael", "Informe: Gula evoluiu para BELZEBU, Senhor da Gula. Análise da Prisão Infinita... concluída. Veldora pode ser libertado."],
		["Veldora", "KUAHAHAHA! LIVRE! Finalmente! Rimuru, meu amigo, que mundo é esse?!"],
		["Rimuru", "Bem-vindo de volta, Veldora. Agora... vamos trazer todos de volta."],
		["Shion", "(Revivendo) ...Rimuru-sama? Eu... voltei? Rimuru-samaaaa!"],
		["Rimuru", "(Usando o círculo de invocação com corpos de soldados) Venha, demônio! ...Um demônio primordial respondeu?"],
		["Diablo", "Kufufufu... Eu sou um demônio sem nome. Deixe-me servi-lo para sempre, Rimuru-sama. ...'Diablo'? Que nome magnífico!"]]},
	{"t": "reward", "forms": ["demon_lord"], "skills": ["raphael", "megiddo", "beelzebuth", "storm_dragon", "demon_aura"], "allies": ["diablo"], "town": 5, "level": 5, "title": "Rimuru Tempest, Lorde Demônio", "hp": 300, "mp": 300, "msg": "Você virou Lorde Demônio! Forma Lorde Demônio, Megiddo, Belzebu, Tempestade de Veldora, Aura. Diablo entrou no grupo."},
	# ------------------------------------------------------------ Cap. 9
	{"t": "chapter", "n": 9, "title": "Walpurgis", "sub": "O Banquete dos Lordes Demônio"},
	{"t": "dialog", "lines": [
		["Ramiris", "Rimuru! Clayman convocou uma Walpurgis! Ele disse que você atacou a Milim! E a Milim está do lado dele, toda estranha!"],
		["Diablo", "Kufufu... Clayman é quem armou o ataque de Falmuth. Ele manipula todos como marionetes."],
		["Rimuru", "Então eu vou à festa. E vou acabar com ele lá mesmo."]]},
	{"t": "obj", "kind": "area", "area": "walpurgis", "pos": Vector3(135, 0, -135), "text": "Vá ao salão da Walpurgis (portal a sudeste da floresta)."},
	{"t": "obj", "kind": "talk", "npc": "guy", "area": "walpurgis", "text": "Apresente-se a Guy Crimson, o Lorde Demônio mais antigo."},
	{"t": "dialog", "lines": [
		["Guy Crimson", "Então você é o slime que virou Lorde Demônio. Clayman te acusa. Prove sua força aqui."],
		["Clayman", "Hahaha! Milim é minha marionete! Esse slime vai morrer diante de todos os Lordes!"],
		["Rimuru", "Clayman. Você mandou matar meu povo. Hoje você paga."]]},
	{"t": "obj", "kind": "boss", "area": "walpurgis", "enemy": "clayman", "spawn": [["clayman", 1, Vector3(0, 0, 0), 0.0]], "pos": Vector3(0, 0, 0), "text": "Derrote Clayman, o Marionetista!"},
	{"t": "dialog", "lines": [
		["Milim", "Wahaha! Te enganei, Clayman! Eu nunca estive sob controle! Só queria ver o que você ia fazer."],
		["Clayman", "N-Não... Laplace... me ajude..."],
		["Guy Crimson", "Decidido. Rimuru Tempest é um Lorde Demônio. E não somos mais 'Dez': agora somos o OCTAGRAMA, as Oito Estrelas Lordes Demônio."],
		["Ramiris", "Rimuru é nosso! Ehh... e eu vou morar em Tempest também!"]]},
	{"t": "reward", "allies": ["milim"], "level": 3, "hp": 200, "mp": 150, "title": "Rimuru Tempest, Octagrama", "msg": "Você agora é um dos Octagrama! Milim entrou no grupo e Ramiris trouxe o Labirinto para Tempest."},
	# ------------------------------------------------------------ Cap. 10
	{"t": "chapter", "n": 10, "title": "Hinata Sakaguchi", "sub": "A Cavaleira Sagrada"},
	{"t": "dialog", "lines": [
		["Souei", "Relatório: Hinata Sakaguchi, capitã dos Cavaleiros Sagrados, está vindo sozinha. Ela acha que o senhor matou Shizu."],
		["Rimuru", "Aluna da Shizu-san... Eu preciso falar com ela. Mas parece que ela não vai ouvir."]]},
	{"t": "obj", "kind": "reach", "area": "forest", "pos": Vector3(120, 0, -75), "r": 18.0, "text": "Encontre Hinata na estrada leste."},
	{"t": "dialog", "lines": [
		["Hinata", "Monstro que devorou minha professora. Não há perdão. Vou te apagar com a Desintegração."],
		["Rimuru", "Escuta! A Shizu me pediu para cuidar das crianças! ...Tá. Primeiro eu sobrevivo, depois a gente conversa."]]},
	{"t": "obj", "kind": "boss", "area": "forest", "enemy": "hinata", "spawn": [["hinata", 1, Vector3(125, 0, -80), 0.0]], "pos": Vector3(125, 0, -80), "text": "Vença o duelo contra Hinata Sakaguchi!"},
	{"t": "dialog", "lines": [
		["Hinata", "...Você poderia ter me matado. Por que parou?"],
		["Rimuru", "Porque a Shizu-san gostava de você. Ela deixou uma carta. Leia."],
		["Hinata", "(Lendo) ...Sensei. ...Eu errei, Rimuru. A Igreja estava sendo manipulada. Desculpe."],
		["Raphael", "Informe: análise da magia sagrada 'Desintegração' concluída. Reprodução possível."]]},
	{"t": "reward", "skills": ["disintegration"], "level": 2, "msg": "Paz com a Igreja Ocidental! Skill: Desintegração."},
	# ------------------------------------------------------------ Cap. 11
	{"t": "chapter", "n": 11, "title": "Festival e Guerra Imperial", "sub": "Arco do Império Oriental (mangá)"},
	{"t": "dialog", "lines": [
		["Rigurd", "O Festival dos Fundadores foi um sucesso! Até o Rei Gazel e a Imperatriz Elmesia vieram!"],
		["Ramiris", "E o meu Labirinto é a atração principal! Ninguém passou do Veldora no 100º andar! Hehe!"],
		["Benimaru", "Rimuru-sama... notícias ruins. O Império Oriental invadiu com quase um milhão de soldados e tanques mágicos."],
		["Rimuru", "Então vamos mostrar ao Império o que Tempest pode fazer. Todos, comigo!"]]},
	{"t": "obj", "kind": "kill", "area": "forest", "enemy": "imperial_soldier", "count": 15, "spawn": [["imperial_soldier", 10, Vector3(125, 0, 15), 16.0], ["magic_tank", 3, Vector3(140, 0, 20), 12.0], ["imperial_soldier", 8, Vector3(110, 0, 30), 14.0]], "pos": Vector3(125, 0, 15), "text": "Repela a invasão imperial (leste): derrote 15 soldados."},
	{"t": "obj", "kind": "boss", "area": "forest", "enemy": "kondo", "spawn": [["kondo", 1, Vector3(135, 0, 10), 0.0]], "pos": Vector3(135, 0, 10), "text": "Derrote o Tenente-Coronel Kondo!"},
	{"t": "dialog", "lines": [
		["Kondo", "...Impressionante, Lorde Demônio. Mas o verdadeiro inimigo não sou eu."],
		["Yuuki", "Olá, Rimuru-san. Obrigado por enfraquecer o Império para mim. Agora o mundo será meu."],
		["Rimuru", "Yuuki?! Você... era o líder dos Moderate Harlequin esse tempo todo?!"],
		["Yuuki", "Sim. Clayman, Laplace, tudo foi meu plano. Agora some."]]},
	{"t": "obj", "kind": "boss", "area": "forest", "enemy": "yuuki", "spawn": [["yuuki", 1, Vector3(120, 0, 0), 0.0]], "pos": Vector3(120, 0, 0), "text": "BATALHA FINAL: derrote Yuuki Kagurazaka!"},
	{"t": "dialog", "lines": [
		["Yuuki", "Impossível... meu poder... está sendo devorado?!"],
		["Raphael", "Proposta: assumir o controle de todas as habilidades e lutar ao lado de Rimuru para sempre. Para isso... preciso de um nome."],
		["Rimuru", "Raphael... você sempre esteve comigo. Seu nome a partir de hoje é CIEL."],
		["Ciel", "Entendido, Mestre. Eu sou Ciel. Prazer em conhecê-lo de verdade."],
		["Veldora", "KUAHAHAHA! Tempest venceu! Vamos fazer um banquete! E o Rimuru paga o mangá!"],
		["Rimuru", "Monstros e humanos vivendo juntos e felizes... Esse é o país que eu queria criar."]]},
	{"t": "reward", "skills": ["ciel_passive", "ciel_mode"], "level": 5, "hp": 500, "mp": 500, "title": "Rimuru Tempest, Deus Demônio", "msg": "Raphael virou CIEL! Skill: Ciel: Batalha Automática."},
	{"t": "end"},
	# ------------------------------------------------------------ Epílogo
	{"t": "chapter", "n": 12, "title": "Epílogo", "sub": "Jogo livre em Tempest"},
	{"t": "obj", "kind": "free", "text": "Jogo livre! Explore, treine com Veldora (fale com ele em Tempest), devore monstros e suba de nível."},
]
